//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres, Inspired by Juanpe Catalán VIPER Template
//

import UIKit

class ___VARIABLE_productName:identifier___RemoteDataManager: ___VARIABLE_productName:identifier___RemoteDataManagerInputProtocol {



		var remoteRequestHandler: ___VARIABLE_productName:identifier___RemoteDataManagerOutputProtocol? 
   
}
