//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres
//

import UIKit

class ___VARIABLE_productName:identifier___Wireframe: ___VARIABLE_productName:identifier___WireframeProtocol {

    weak var viewController: UIViewController?


    //If you dont want to pass data from a VIPER-X Module to another remove tha param data_to_pass from the function
    static func createModule(with data_to_pass:Int) -> UIViewController {
        let navController = ___VARIABLE_productName:identifier___storyboard.instantiateViewController(withIdentifier: "storyboard_id")
        if let view = navController.children.first as? ___VARIABLE_productName:identifier___ViewProtocol {

        let interactor : ___VARIABLE_productName:identifier___InteractorInputProtocol & ___VARIABLE_productName:identifier___RemoteDataManagerOutputProtocol    =  ___VARIABLE_productName:identifier___Interactor()
        let router : ___VARIABLE_productName:identifier___WireframeProtocol =  ___VARIABLE_productName:identifier___Wireframe()
       
        let presenter: ___VARIABLE_productName:identifier___PresenterProtocol & ___VARIABLE_productName:identifier___InteractorOutputProtocol = ___VARIABLE_productName:identifier___Presenter()

        let remoteDataManager : ___VARIABLE_productName:identifier___RemoteDataManagerInputProtocol = ___VARIABLE_productName:identifier___RemoteDataManager()




            view.presenter = presenter
            presenter.view = view
            presenter.wireFrame = router
            presenter.interactor = interactor
            interactor.presenter = presenter
            interactor.remoteDataManager = remoteDataManager
            remoteDataManager.remoteRequestHandler = interactor
		     return navController

}
            return UIViewController()

    }


   static var ___VARIABLE_productName:identifier___storyboard: UIStoryboard {
        return UIStoryboard(name: "Write the name of you storyboard here", bundle: Bundle.main)
    }




}
