//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres, Inspired by Juanpe Catalán VIPER Template
//

import UIKit

class ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorInputProtocol, ___VARIABLE_productName:identifier___RemoteDataManagerOutputProtocol {

    weak var presenter: ___VARIABLE_productName:identifier___InteractorOutputProtocol?
    var remoteDataManager:___VARIABLE_productName:identifier___RemoteDataManagerInputProtocol?
}

